### ISSUE TITLE
What should "Respect privacy" entail?

### ISSUE THREAD

**Issue by duplode** [snoyberg/stack-coc#7]
On the "respect privacy" section of the communications guide, I see where @gbaz is coming from with "it seems to [...] introduce the principle only to immediately introduce language that undermines it", so I will attempt to reconstruct the point being made in that section, looking for ways we might make it sharper.

The motivation for the "if both sides agree" caveat is that an universal and automatic expectation of privacy can be abused. For instance, a bad actor might run a smear campaign against a third party using private messages. The current version of the guidelines addresses that by requiring an agreement reached upon "a private message requesting the other side participate privately". I presume this preliminary message would have to truthfully indicate the nature of what would be discussed. That being so, the aforementioned bad actor would have to ask something to the effect of "I have some hot gossip about Z. Wanna hear it?", at which point the recipient would be able to decline taking further part in the exchange.

Under such an interpretation, I believe the guideline is not contradictory. There is, however, another difficulty. Suppose that a fellow Haskeller sends me, without asking me beforehand, a personal message which includes personal information about their background and life story that, in principle, would be no one else's business. Should I have the right to share this personal information just because there was no preliminary message? Clearly not -- that would be against the spirit of the guideline, not to say against basic human decency. The one way out I see, and I know it is a bit of a minefield, is accounting for the content of the private messages when deciding whether there should be safe harbour for them. It might look like this:

> On occasion, holding certain discussions in private can be the prudent or kind thing to do. However, private communications can also be used as a means for attacks and intimidation. As such, a message can only be reasonably considered as private *if what it says does not affect anyone other than the sender*, or if there was a previous agreement between sender and recipient about its privacy. If in doubt, send a preliminary message asking the other party to participate privately.
>
> Somewhat obviously: if there is a reasonable expectation of privacy **do not** violate it!

Some examples of how that "does not affect anyone other than the sender" clause might work, in the absence of a previous agreement:

* X tells Y their opinion on a GHC proposal: reasonably private; no one is personally affected.
* X tells Y private matters about themselves: reasonably private; only X is affected.
* X insults Y: not reasonably private; Y is affected.
* X tells Y gossip about Z: not reasonably private; Z is affected.

There certainly are thorny corner cases here. For instance, a preliminary message saying "I have some hot gossip about Z" would arguably already contain an insinuation about Z. Still, it is probably not a good idea to rely on much more than the wise judgment of the involved parties to deal with the corner cases, as adding minute detail to those guidelines would be a hopeless endeavour.

**Comment by snoyberg** [comment]
Thank you for the clarification. I absolutely believe this section is both necessary and non-contradictory.

On the "necessary" front, let me describe in a bit more detail the kinds of situations I'm concerned with, since it may help clarify how I've worded things until now, and why I wouldn't be comfortable with the proposed new language. I'm worried about threats, demands, or other such material being sent privately. For example:

> You're a moron. If you don't change your stance on this publicly, I will find ways to change the upstream tooling you depend upon to cause you breakage.

Or more extreme:

> I know where you live and I'm going to cause you physical harm.

Note that I'm _not_ claiming that anything like this happened. I'm saying that this is the kind of intimidation and threatening language that can be sent privately, and then a shield of "presumed privacy" can be used to protect the sender from any repercussions.

I'd be OK with including language which said something like "whenever reasonable" or similar, you should respect the privacy of others. But I can't imagine any kind of blanket requirement of ensured private communication without prior agreement.

**Comment by duplode** [comment]
@snoyberg The way I had thought of it, threats in private messages would fall into the recipient being "affected" by what the message says (among the examples I gave, "X threatens Y" would have been just as good as "X insults Y"). I can see how "affect" might be too vague a verb to make that clear; I couldn't think of anything better yet.

(By the way, here is another conceivable scenario to think about: a bad actor who unwittingly reveals in a private message that they are secretly acting to sabotage a community initiative, or that they are using sockpuppets to manipulate discussions.)

**Comment by snoyberg** [comment]
Both of those scenarios are interesting ones to consider. I suppose the "affect others" argument would apply. However, it's not really a threat. This kind of reminds me of the doctor-patient confidentiality, where a doctor is required to keep all discussions private, unless it's a discussion about plans to commit a crime in the future. This _almost_ sounds like "keep private conversations private, unless there's legitimate concern that someone is planning something bad."

But getting into those details sounds like over-legislating. I'm still leaning towards a "respect privacy whenever reasonable" sentiment.

**Comment by snoyberg** [comment]
If you don't mind, I'm going to close this out now, as I don't think there's an improved wording available for the moment.

**Comment by duplode** [comment]
@snoyberg It is all right. I almost submitted a pull request based on this discussion, but it turned out even I wasn't truly satisfied with the wording I'd suggest.
